spring:
  application:
    name: protel-api
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: connection-init-sql=SET time_zone='+00:00'
  security:
    user:
      name: ${API_BASIC_USER}
      password: ${API_BASIC_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
     hibernate: jdbc:time_zone=UTC


server:
  port: 8085
  address: 127.0.0.1
  forward-headers-strategy: framework



protel:
  base-url: ${PROTEL_BASE_URL}
  api-key: ${PROTEL_API_KEY}
  max-responses: 100
  overlap-seconds: 600
  direct-booking:
    distribution-channels:
          - "WEB"



wordpress:
  base-url: ${WP_BASE_URL}
  award-endpoint: ${WP_AWARD_ENDPOINT}
  shared-secret: ${WP_SHARED_SECRET}
  timeout-seconds: 15

